ALTER TABLE "Company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Driver" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vehicle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MobilityService" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProviderLocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FleetTransaction" ENABLE ROW LEVEL SECURITY;
