import { createSession, requireSession, type SessionUser, verifyPassword } from './auth.ts'

function assert(condition: unknown, message: string) {
	if (!condition) {
		throw new Error(message)
	}
}

Deno.test('verifies passwords generated by the Node API', async () => {
	const storedPassword = 'pbkdf2_sha256$310000$test-salt$s3LaJTQ3iJs8y363Th3H_5Zw27Xq4f1shIKbuhreaMk'
	assert(await verifyPassword('demo1234', storedPassword), 'expected the correct password to pass')
	assert(!(await verifyPassword('wrong-password', storedPassword)), 'expected an incorrect password to fail')
})

Deno.test('creates and verifies a stateless session', async () => {
	const user: SessionUser = {
		id: 'user-admin',
		name: 'Admin User',
		email: 'admin@example.com',
		role: 'fleet_admin',
		companyName: 'FleetOps Demo',
	}
	const secret = 'test-session-secret-with-at-least-32-characters'
	const token = await createSession(user, 'demo-company', secret)
	const request = new Request('https://example.com/workspace', {
		headers: { authorization: `Bearer ${token}` },
	})
	const session = await requireSession(request, secret)

	assert(session.id === user.id, 'expected the user ID to survive token verification')
	assert(session.companyId === 'demo-company', 'expected the company ID to survive token verification')
})
