import { verifyPassword } from './passwords.ts'

function assert(condition: unknown, message: string) {
	if (!condition) {
		throw new Error(message)
	}
}

Deno.test('verifies passwords generated by the Node API', async () => {
	const storedPassword = 'pbkdf2_sha256$310000$test-salt$s3LaJTQ3iJs8y363Th3H_5Zw27Xq4f1shIKbuhreaMk'
	assert(await verifyPassword('demo1234', storedPassword), 'expected the correct password to pass')
	assert(!(await verifyPassword('wrong-password', storedPassword)), 'expected an incorrect password to fail')
})
